### ISSUE TITLE
Help with setting bot up

### ISSUE THREAD

**Issue by hiphoprexx** [moonstar-x/discord-music-24-7#13]
Hello, I'm trying to install the bot on Ubuntu could someone help me?

  Regards,
     Ryan

**Comment by hiphoprexx** [comment]
You can contact me via discord it will be easier for me :D 

Ryan DeTree#4293
or
Lap-Corp™#0908

**Comment by moonstar-x** [comment]
Sorry for taking a bit long to answer this. I've sent you a friend request and will continue from there! :)
