### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Biolude** [moonstar-x/discord-music-24-7#14]
It keeps repeating that ffmpeg isnt installed idk how to fix it even tho i have it installed

**Comment by moonstar-x** [comment]
If it says that `ffmpeg` isn't installed it most likely isn't in your PATH. Try running in a terminal/cmd window

```
ffmpeg -v
```

And check if there's a positive output.

**Comment by Biolude** [comment]
thanks for the fast response yes i tried that but for some reason its still not working

**Comment by Biolude** [comment]
says not a regonized batch file

**Comment by Biolude** [comment]
i downloaded it from the link you put it in the discord-music-24-7 folder

**Comment by Biolude** [comment]
i dont know what file to link to in path

**Comment by moonstar-x** [comment]
> i dont know what file to link to in path
> 
> 

If you checked the README and downloaded ffmpeg from there you may have noticed that it came in a zip with multiple other files. You'll want to unzip this somewhere in your hard drive, (maybe `C:\bin`) and follow the steps in [this link](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/) where you'll want to add `C:\bins` (or whatever folder you created where `ffmpeg.exe` is located) into the PATH variable.

Once that's done, running `ffmpeg -v` in your console should yield a version message.

**Comment by Biolude** [comment]
sorry just realized oh downloaded the source code stupid me. So i just have to add to path right. the c:\ bins doesn't have to be in discord music 24-7 right?

**Comment by moonstar-x** [comment]
> sorry just realized oh downloaded the source code stupid me. So i just have to add to path right. the c:\ bins doesn't have to be in discord music 24-7 right?

Indeed, you add the binary in a folder that is easy for you to remember and add that folder directory to the PATH.

**Comment by Biolude** [comment]
Thanks for the help I got it to work!

**Comment by Biolude** [comment]
hmm its not playing
 music in the vc tho

**Comment by Biolude** [comment]
nvm its all good. Sorry for troubling you so much

**Comment by moonstar-x** [comment]
Alright, no problem, glad to know it works. If you need any more help feel free to open a new issue!

**Comment by Biolude** [comment]
alr ty
