### ISSUE TITLE
Error on Heruko

### ISSUE THREAD

**Issue by thangjin207** [moonstar-x/discord-music-24-7#19]
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
Could u help me to solve this error?
Tks.

**Comment by moonstar-x** [comment]
I noticed that your Procfile contains `worker: node src/index`, there's no `index.js` file, the entrypoint of the bot is `src/app.js`. Change your Procfile to `worker: npm start`.

Then, make sure that `web` dyno is turned off and that your `worker` dyno is on.

Lastly, on your heroku application, head over to settings and then, under buildpacks, add the following:

https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git
And finally restart the dyno.

This will install ffmpeg on your dyno.

**Comment by thangjin207** [comment]
it's solved. thank you so much.

**Comment by moonstar-x** [comment]
I'm glad it worked!
