### ISSUE TITLE
Now playing.

### ISSUE THREAD

**Issue by mryansulbi** [moonstar-x/discord-music-24-7#20]
hello sir! i'm new here to creating my own bot. so randomly i find this project and i'm so excited with this project.
And thank you very much.
so, i have a question. it is possible change the now playing from the status to channelmessage? 
if dont mind, can you tell me how to do that? 
so its okay if you dont wanna to anwser my question. 

THANK YOU :D

**Comment by moonstar-x** [comment]
Hey there, if you wish to change this, fork this repo and inside `src/classes/Player.js` you'll need to change the implementation of the `updatePresence()` method so the bot's status gets updated to what you want.

**Comment by mryansulbi** [comment]
thank you for answering me, 
so i should change the updatePresence() to channel message?
i want to my bot send now playing in the status to the channel message, like this sir
![zc](https://user-images.githubusercontent.com/51363500/99831848-4e12b300-2b92-11eb-87cf-794e8019812c.PNG)

anyway, sorry if my english is bad
THANK YOU

**Comment by moonstar-x** [comment]
Ahhh, that's way different, I thought you were talking about the bot's presence.

You would need to have the text channel ID saved somewhere and when the bot starts up you would fetch the channel, save its reference and everytime the bot changes it's song send a message like that. Currently the bot does not do that so you would need to implement that yourself.

**Comment by mryansulbi** [comment]
AHHH THANK YOU VERY MUCH... 
i'll try that method, thank you sir.

**Comment by moonstar-x** [comment]
Good luck!

**Comment by hezaaheza** [comment]
![image](https://user-images.githubusercontent.com/53120237/100489614-d28fa380-3147-11eb-8b45-bc53591d969d.png)
MANN... THANKS, worked to me :D
