### ISSUE TITLE
Add more Playable Domains

### ISSUE THREAD

**Issue by FoxXxHater** [moonstar-x/discord-music-24-7#37]
Hay there,

is there a way to add more playable Domains like these: "http://stream.laut.fm/foxco-radio"?

have a nice day!

**Comment by moonstar-x** [comment]
Sorry for the late response. I think this should be indeed possible and easy to implement.

Right now I'm kinda super busy with uni so there's no chance I can work on this any time soon. My semester ends in about a month, which means I will be able to work on this after that.

Thanks for the suggestion!

**Comment by moonstar-x** [comment]
Sorry for taking long with this. It's been added in #49.

Please, update your bot by pulling the changes from master:

```text
git pull origin master
```

And make sure to check the README once again, I've added some breaking changes that will most likely change how you configure your bot.
