### ISSUE TITLE
error (avconv missing file)

### ISSUE THREAD

**Issue by JackeLeMort** [moonstar-x/discord-music-24-7#46]
when i type "npm start" in my cmd the bot connect to the channel but plays nothing, and the cmd report non-stop that there's a missing file, the files is "avconv" what should be in the "ffmpeg" folder but there is no such file so i don't know what to do, if someone could help me 🤷‍♂️

here a screen of the error :
![image](https://user-images.githubusercontent.com/84813895/120907177-b7a26c80-c65f-11eb-8a78-376c34950ca0.png)

thank you for your help, have a nice day and please excuse my english, i'm french

**Comment by moonstar-x** [comment]
The bot is telling you that you don't have ffmpeg installed. You can test if you have it installed by typing `ffmpeg -v` in the console.

This [guide](https://techcult.com/install-ffmpeg-on-windows-10/) explains how to install this.

**Comment by JackeLeMort** [comment]
it seems to be installed 🤔 
![image](https://user-images.githubusercontent.com/84813895/120908122-9180ca80-c667-11eb-8904-08ccf54ef422.png)

**Comment by moonstar-x** [comment]
The command is `ffmpeg -v`, not `npm ffmpeg -v`.

**Comment by JackeLeMort** [comment]
okay, i did what the guide said, i didn't do it the first time, and now when i type the rught command i got this : 
![image](https://user-images.githubusercontent.com/84813895/120908330-68613980-c669-11eb-9cec-a9e2d0d75a44.png)

**Comment by moonstar-x** [comment]
Alright it seems to be installed now, try restarting the bot now it should no longer display that error.

**Comment by JackeLeMort** [comment]
Yeah it's working ! Thank you very much, and have a nice day !
