### ISSUE TITLE
MinigetError: Status Code: 404 - YouTube

### ISSUE THREAD

**Issue by JackeLeMort** [moonstar-x/discord-music-24-7#47]
so, i come again for a new problem, i tried to fix it myself, but i didn't find de true problem

when i start the console first show this : 
![image](https://user-images.githubusercontent.com/84813895/122981602-3a366600-d39a-11eb-82d3-2c616b423a3e.png)
for a little time, then show this : 
![image](https://user-images.githubusercontent.com/84813895/122981657-49b5af00-d39a-11eb-8ea9-1d21a013f7c8.png)
and finaly spamm the same error again and again : 
![image](https://user-images.githubusercontent.com/84813895/122981767-65b95080-d39a-11eb-889d-5b7c1e0200c2.png)

i don't find the problem so i come ask for your help

edit : 
and i forgot to say that the bot is actually connected to the voice channel, with a gren circle around his pdp, but i don't hear a sound

**Comment by moonstar-x** [comment]
Hello there, do you know which link in your queue is causing this?

Can you share what you have in your `queue.txt` file?

**Comment by moonstar-x** [comment]
Actually looking through my email I spotted that a new issue came up in the library I use for YouTube support. It seems you're not the only one with [this issue](https://github.com/fent/node-ytdl-core/issues/939).

I'm gonna wait for an update on their part since it sounds like someone already found a fix.

**Comment by JackeLeMort** [comment]
in fact i thouhgt it was that, and removed the old links, but maybe i didn't see something so :
[queue.txt](https://github.com/moonstar-x/discord-music-24-7/files/6696819/queue.txt)

**Comment by JackeLeMort** [comment]
okay thank you

**Comment by JackeLeMort** [comment]
did you find something ?
