### ISSUE TITLE
Error happening when I start

### ISSUE THREAD

**Issue by Edison12300** [moonstar-x/discord-music-24-7#59]
#### :confused: Question

> When I use the start command, this error always pops up. Saw that someone had the same error, but when I tried the way that he fixed his, it still doesn't work. I'm running this on a raspberry pi 4.

#### :question: Additional Information

> 
![image](https://user-images.githubusercontent.com/71360570/134915508-d07ab208-e114-45a8-a66e-b98f7e176d06.png)

**Comment by moonstar-x** [comment]
Hello there, the error is telling you that you haven't set the `channel_id` setting inside the `settings.json` file, you need to add the ID of the channel that the bot should join.

**Comment by Edison12300** [comment]
I did add the ID of the voice channel in the settings though.

**Comment by moonstar-x** [comment]
Have you renamed the `settings.json.example` file to `settings.json`?

**Comment by Edison12300** [comment]
I've found out what's wrong. My settings was called setting.json.
Quick question, how do I add the music I want to play?

**Comment by moonstar-x** [comment]
No prob,

Inside the `data` folder, there's a `queue.txt' file, you can add the youtube, soundcloud or direct stream URLs there. There's a `local-music` folder inside that `data` folder, there you can add the `.mp3` and `.m4a` files if you have your own music files.

**Comment by moonstar-x** [comment]
> I've found out what's wrong. My settings was called setting.json.

In any case, I'm gonna close this issue since it seems that you've fixed your problem.
