### ISSUE TITLE
Bot skipping song that didn't end.

### ISSUE THREAD

**Issue by jc-discdev** [moonstar-x/discord-music-24-7#72]
#### :bug:

> A clear and concise description of what the bug is.
The bot stops playing and gives an error, then skips song.
#### :pencil2: Steps to Reproduce

> 1. Play the queue
> 2. Wait
> 3. It happens
#### :confused: Expected Behavior
It skips to next song.
> A description of what you expected to get (if applicable).
It should continue playing it as normal.
#### :scroll: Log

``` text
(1:50:50 PM) - [ERROR] -  Error: aborted
    at connResetException (node:internal/errors:692:14)
    at TLSSocket.socketCloseListener (node:_http_client:402:19)
    at TLSSocket.emit (node:events:539:35)
    at node:net:688:12
    at TCP.done (node:_tls_wrap:582:7) {
  code: 'ECONNRESET'
}
```

#### :camera: Screenshots

> Paste a screenshot of the bug (if applicable).

#### :question: Other Information

* Node Version: `v17.`

**Comment by moonstar-x** [comment]
After what you sent me on Discord it would seem like your VPS does not allow incoming connections.

In any case, I'm glad that using local files works fine for you.
