### ISSUE TITLE
Repl.it supported

### ISSUE THREAD

**Issue by Fyphen1223** [moonstar-x/discord-music-24-7#88]
#### :bug: Describe the Bug
FFmpeg on repl.it is supported. FFmpeg is not supported, but ffmpeg-static is alternatives of ffmpeg.
> A clear and concise description of what the bug is.

#### :pencil2: Steps to Reproduce

> 1. Go to '...'
> 2. Type '...'
> 3. See error...

#### :confused: Expected Behavior

> A description of what you expected to get (if applicable).

#### :scroll: Log

``` text
Paste a relevant portion of the console log here.
```

#### :camera: Screenshots

> Paste a screenshot of the bug (if applicable).

#### :question: Other Information

* Node Version: `Version of the node runtime.`

**Comment by moonstar-x** [comment]
Hi, I've seen that this sometimes work, sometimes it doesn't.

In any case, for anybody wondering, you can install `ffmpeg-static` with:

```text
npm install --save-dev ffmpeg-static
```

I'll close this because I assume that this isn't really a bug report but more as a heads up for repl.it users.
